# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/adu4',
                'doc_host': 'https://luihzpg.github.io',
                'git_url': 'https://github.com/luihzpg/adu4',
                'lib_path': 'adu4'},
  'syms': { 'adu4.core': { 'adu4.core.extract_tweets_from_file': ('twitterscraper.html#extract_tweets_from_file', 'adu4/core.py'),
                           'adu4.core.scrape_twitter_page': ('twitterscraper.html#scrape_twitter_page', 'adu4/core.py')}}}
